### ISSUE TITLE
Sources of data

### ISSUE THREAD

**Issue by oblique** [dtrihinas/covid-19-cyprus-data#1]
From where do you get the data?
If you wrote a script, can you share it?

**Comment by dtrihinas** [comment]
Hi @oblique there is not data stream or official data repository made available by the goverment. That is why I am manually compiling this dataset. My sources are the official goverment announcements (pdfs can be found here https://www.pio.gov.cy/coronavirus/) and trawling the islands media outlets to assemble as much of the missing data.

**Comment by oblique** [comment]
I see. This is going to be a problem soon.

**Comment by dtrihinas** [comment]
unfortunately yes... I'm trying to mitigate this to the committee because right now info is given here and there without considering the future.
